openapi: 3.0.3
info:
  title: Hlasovací systém
  version: 1.0.11
paths:
  /pdf/SK:
    get:
      tags:
        - pdf
      summary: Creates a pdf from manual page in Slovak
      description: Creates a pdf from manual page in Slovak
      responses:
        '200':
          description: OK
  /pdf/EN:
    get:
      tags:
        - pdf
      summary: Creates a pdf from manual page in English
      description: Creates a pdf from manual page in English
      responses:
        '200':
          description: OK
  /answer:
    post:
      tags:
        - answer
      summary: Add an answer to question
      description: Add answer to question
      operationId: createAnswer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostAnswer'
          application/xml:
            schema:
              $ref: '#/components/schemas/PostAnswer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostAnswer'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Error

  /answer/delete/{answerId}:
    post:
      tags:
        - answer
      summary: Delete an answer
      description: Delete an answer
      operationId: deleteAnswer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/xml:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccessToken'
        required: true
      parameters:
        - name: answerId
          in: path
          description: Answer id to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /answer/{answerId}:
    put:
      tags:
        - answer
      summary: Update an existing answer by id
      description: Update an existing answer by id
      operationId: updateAnswer
      parameters:
        - name: answerId
          in: path
          description: Answer id to be updated
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutAnswer'
          application/xml:
            schema:
              $ref: '#/components/schemas/PutAnswer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PutAnswer'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /{code}:
    get:
      tags:
        - question
      summary: Get question with code
      operationId: getQuestionWithCode
      parameters:
        - name: code
          in: path
          description: Code of the question to be fetched
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuestion'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /question/{questionId}/answers:
    get:
      tags:
        - question
      summary: Get all answers to a question
      operationId: getAllQuestionAnswers
      parameters:
        - name: questionId
          in: path
          description: Fetch this QuestionId's answers
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAnswers'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetAnswers'
        '400':
          description: Error
  /question/export:
    get:
      tags:
        - question
      summary: Export all questions and answers
      operationId: exportAllQuestionsAndAnswers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportAllQuestionsForAdmin'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExportAllQuestionsForAdmin'
        '400':
          description: Error
  /question/user/{userId}/export:
    get:
      tags:
        - question
      summary: Export all user questions and answers
      operationId: exportAllQuestionsAndAnswers
      parameters:
        - name: userId
          in: path
          description: Export this UserId's questions
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportAllQuestionsByUserId'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExportAllQuestionsByUserId'
        '400':
          description: Error
  /question/user/{userId}:
    post:
      tags:
        - question
      summary: Get question with user id
      operationId: getQuestionByUserId
      parameters:
        - name: userId
          in: path
          description: Fetch this UserId's questions
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuestionsByUserId'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetQuestionsByUserId'
        '400':
          description: Error
  /question:
    post:
      tags:
        - question
      summary: Create a question
      operationId: createQuestion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostQuestion'
          application/xml:
            schema:
              $ref: '#/components/schemas/PostQuestion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PostQuestion'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  code:
                    type: string    # Added code property
        '400':
          description: Error
  /question/delete/{questionId}:
    post:
      tags:
        - question
      summary: Delete question by id
      operationId: deleteQuestion
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/xml:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccessToken'
        required: true
      parameters:
        - name: questionId
          in: path
          description: ID of the question to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /question/{questionId}:
    post:
      tags:
        - question
      summary: Get question by id
      operationId: getQuestionbyId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/xml:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccessToken'
        required: true
      parameters:
        - name: questionId
          in: path
          description: ID of question that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetQuestion'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetQuestion'
        '400':
          description: Error
    put:
      tags:
        - question
      summary: Update a question
      operationId: updateQuestion
      parameters:
        - name: questionId
          in: path
          description: ID of question that needs to be updated
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutQuestion'
          application/xml:
            schema:
              $ref: '#/components/schemas/PutQuestion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PutQuestion'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /user/list:
    post:
      tags:
        - user
      summary: Get all users
      operationId: getUsers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/xml:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccessToken'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUser'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetUser'
        '400':
          description: Error
  /user:
    post:
      tags:
        - user
      summary: Create user
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /user/login:
    post:
      tags:
        - user
      summary: Login
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
          application/xml:
            schema:
              $ref: '#/components/schemas/LoginUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
            application/xml:
              schema:
                $ref: '#/components/schemas/Login'
        '400':
          description: Error
  /user/username:
    post:
      tags:
        - user
      summary: Checks if username is in database
      operationId: checkUsername
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckUser'
          application/xml:
            schema:
              $ref: '#/components/schemas/CheckUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CheckUser'
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /user/delete/{userId}:
    post:
      tags:
        - user
      summary: Delete user
      operationId: deleteUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/xml:
            schema:
              $ref: '#/components/schemas/AccessToken'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AccessToken'
        required: true
      parameters:
        - name: userId
          description: Id of user that need to be deleted
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
        '400':
          description: Error
  /user/{userId}:
    put:
      tags:
        - user
      summary: Update user
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          description: Id of user that need to be updated
          required: true
          schema:
            type: string
      requestBody:
        description: Update an existent user in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/xml:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
        '400':
          description: Error

components:
  schemas:
    AccessToken:
      type: object
      properties:
        access_token:
          type: string
      xml:
        name: user
    CheckUser:
      type: object
      properties:
        username:
          type: string
      xml:
        name: user
    LoginUser:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      xml:
        name: user

    ExportAllQuestionsForAdmin:
      type: object
      properties:
        questions:
          type: object
          properties:
            id:
              type: integer
            user_id:
              type: integer
            date:
              type: string
            subject:
              type: string
            question:
              type: string
            type_id:
              type: integer
            code:
              type: string
            answers:
              type: object
              properties:
                id:
                  type: integer
                answer:
                  type: string
                count:
                  type: string
                correct:
                  type: string
      xml:
        name: UserQuestions

    ExportAllQuestionsByUserId:
      type: object
      properties:
        questions:
          type: object
          properties:
            id:
              type: integer
            date:
              type: string
            subject:
              type: string
            question:
              type: string
            type_id:
              type: integer
            code:
              type: string
            answers:
              type: object
              properties:
                id:
                  type: integer
                answer:
                  type: string
                count:
                  type: string
                correct:
                  type: string
      xml:
        name: UserQuestions

    GetQuestionsByUserId:
      type: object
      properties:
        access_token:
          type: string
        question_id:
          type: integer
        date:
          type: integer
        'user_id:':
          type: integer
        type_id:
          type: integer
        code:
          type: string
        qr_code:
          type: string
        question:
          type: string
        subject:
          type: string
        answer:
          type: string
        count:
          type: integer
        correct:
          type: integer
        type:
          type: integer
      xml:
        name: user
    GetAnswers:
      type: object
      properties:

        id:
          type: integer
        answer:
          type: string
        count:
          type: integer
        correct:
          type: integer
      xml:
        name: answer
    GetQuestion:
      type: object
      properties:
        id:
          type: integer
        date:
          type: integer
        'user_id:':
          type: integer
        type_id:
          type: integer
        code:
          type: string
        qr_code:
          type: string
        question:
          type: string
        subject:
          type: string
      xml:
        name: user
    User:
      type: object
      properties:
        access_token:
          type: string
        username:
          type: string
        password:
          type: string
        administrator:
          type: boolean
          format: int1
      xml:
        name: user
    GetUser:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        administrator:
          type: integer
      xml:
        name: user
    PostAnswer:
      type: object
      properties:
        correct:
          type: integer
          format: int1
        answer:
          type: string
        question_id:
          type: integer
      xml:
        name: tag
    PutAnswer:
      type: object
      properties:
        access_token:
          type: string
        correct:
          type: integer
          format: int1
        answer:
          type: string
      xml:
        name: tag
    PutQuestion:
      type: object
      properties:
        access_token:
          type: string
        subject:
          type: string
        question:
          type: string
        type:
          type: string
      xml:
        name: question
    PostQuestion:
      type: object
      properties:
        access_token:
          type: string
        subject:
          type: string
        question:
          type: string
        type:
          type: string
        user_id:
          type: integer
      xml:
        name: question
    Login:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        administrator:
          type: integer
        access_token:
          type: string
    Type:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        type:
          type: string
          example: open_ended
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      xml:
        name: '##default'